---
 title: "Academic Teaching"
 output: html_document
---
### American University 

* **ECON 823 - Econometric Methods (Doctoral):** \
Teaching Assistant for Professor Amos Golan, Fall 2018

* **ECON 824 - Advanced Econometric Methods (Doctoral):** \
Teaching Assistant for Professor Amos Golan, Spring 2019

* **ECON 623 - Applied Econometrics I (Master's):** \
Teaching Assistant for Professor Amos Golan, Spring 2019

* **ECON 803 - Microeconomic Theory I (Doctoral):** \
Teaching Assistant for Professor Sue Bahk, Fall 2020

* **ECON 300 - Intermediate Microeconomics (Undergraduate):** \
Teaching Assistant for Professor Robert Berman, Spring 2019    \
Teaching Assistant for Professor Shirin Sabetghadam, Spring 2020 \
Teaching Assistant for Professor Sue Bahk Fall, 2020

* **ECON 150 - Economics for Business (Undergraduate):** \
Teaching Assistant for Professor Mary Hansen, Spring 2021

* **ECON 100 - Introduction to Microeconomics (Undergraduate):** \
Teaching Assistant for Professor Daniel Lin, Spring 2018          \
Curriculum Development for Professors Mary Hansen and Kara Reynolds, Summer 2020

* **ECON 200 - Introduction to Macroeconomics (Undergraduate):** \
Teaching Assistant for Professor Ivy Broder Fall 2017, Fall 2018 \
Curriculum Development for Professors Mary Hansen and Kara Reynolds, Summer 2020

### Cornell University

* **EDUC 2410 - The Art of Teaching (Undergraduate):** \
Teaching Assistant for Professor Jeff Perry, Spring 2011
